version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase...."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"

  build:
    commands:
      - echo "Pulling base images to avoid rate limiting..."
      - docker pull golang:1.18
      - docker pull alpine:latest
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO_NAME}:latest .
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push ${ECR_IMAGE_URI}
      - echo "Writing image definitions file..."
      - echo '[{"name":"cth2-con","imageUri":"'"${ECR_IMAGE_URI}"'"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

